### ISSUE TITLE
Rework inheritance for renderer

### ISSUE THREAD

**Issue by robin-ynput** [ynput/LabLib#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Initially discussed here: https://github.com/ynput/LabLib/pull/27/files#r1801765261

**For renderer**:
* keep `BasicRenderer` as minimal as possible and rename it `RendererBase`
* move burnins + video/img encoding to a new `SequenceRenderer`
* make `SequenceRenderer` and `SlateRenderer` inherit from `RendererBase`

**For operators**:
* apply same logic for operators  #32 

### How would you imagine the implementation of the feature?

![image](https://github.com/user-attachments/assets/e8196ae7-69b5-4e01-a0e1-967c48f873f5)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by jakubjezek001** [comment]
The inheritance tree looks great. Let's proceed with your suggestion for the rendering workflow. I propose renaming SequenceRenderer to ClipRenderer since the medium could be either video or an image sequence.

Regarding the operators, let's create a separate issue for that. @tweak-wtf, could you please suggest the inheritance structure? We discussed it some time ago in a meeting, and you know the best approach to implement.
